name: BuildDocker

on:
  workflow_dispatch:

jobs:
  build-docker:
    permissions: write-all
    name: Deploy Docker image
    runs-on: ubuntu-22.04
    steps:
      # Actually build the Docker container
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - name: GHCR Log-in
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Container/Dockerfile
          push: true
          # JUNGVI: If you operate from a fork and want to build a new docker make sure to replace 'pulp-platform' by your uname. 
          tags: ghcr.io/pulp-platform/deepquant:main 
