name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:

# JUNGVI: Create a concurrency group per branch such that only the latest commit on a branch runs workflows
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-deepquant:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pulp-platform/deepquant:main
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install DeepQuant in existing venv
        run: |
          uv pip install -e .

  single-layer-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pulp-platform/deepquant:main
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install DeepQuant in existing venv
        run: |
          uv pip install -e .
      - name: Run Tests
        run: |
          pytest -m SingleLayerTests

  model-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pulp-platform/deepquant:main
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install DeepQuant in existing venv
        run: |
          uv pip install -e .
      - name: Run Tests
        run: |
          pytest -m ModelTests -s
