name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build-deepquant:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pulp-platform/deepquant:main
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build DeepQuant
        run: |
          python -m pip install --upgrade pip
          pip install -e .

  single-layer-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pulp-platform/deepquant:main
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build DeepQuant
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run Tests
        run: |
          pytest -m SingleLayerTests

  model-tests:
    runs-on: ubuntu-latest
    # container:
    #   image: ghcr.io/pulp-platform/deepquant:main
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build DeepQuant
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run Tests
        run: |
          pytest -m ModelTests
