name: Linting

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:

  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Format Python Licenses
        run: |
            grep -Lr "SPDX-License-Identifier: Apache-2.0" --exclude-dir=".git" . | grep ".*\.py$" || [[ $? == 1 ]]
        shell: bash
